apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-east1-docker.pkg.dev/sylvan-presence-437615-e6/k8-assignment-artifact-registry/container1:latest
          volumeMounts:
            - name: standard-volume
              mountPath: /malav_PV_dir
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: standard-rwo-pvc
